export const ADD_INTERVIEW_QUESTION="ADD_INTERVIEW_QUESTION";
export const DELETE_INTERVIEW_QUESTION="DELETE_INTERVIEW_QUESTION";
export const ADD_CANDIDATE_DATA="ADD_CANDIDATE_DATA";
export const ADD_PANEL_DATA="ADD_PANEL_DATA";
export const GET_MANAGER="GET_MANAGER";
export const GET_ORGANIZATION_INFO="GET_ORGANIZATION_INFO";
