export const ADD_DEPT_QUESTIONS="ADD_DEPT_QUESTIONS";
export const DELETE_DEPT_QUESTIONS="DELETE_DEPT_QUESTIONS";
export const ADD_JOB_QUESTIONS="ADD_JOB_QUESTIONS";
export const DELETE_JOB_QUESTIONS="DELETE_JOB_QUESTIONS";
export const ADD_MANAGER_QUESTIONS="ADD_MANAGER_QUESTIONS";
export const DELETE_MANAGER_QUESTIONS="DELETE_MANAGER_QUESTIONS";
export const ADD_DEPT_DATA="ADD_DEPT_DATA";
export const ADD_MANAGER_DATA="ADD_MANAGER_DATA";
export const ADD_JOB_DATA="ADD_JOB_DATA";
export const EDIT_DEPT_DATA="EDIT_DEPT_DATA";
export const EDIT_MANAGER_DATA="EDIT_MANAGER_DATA";
export const EDIT_JOB_DATA="EDIT_JOB_DATA";
export const DELETE_DEPT_DATA="DELETE_DEPT_DATA";

export const DELETE_QUESTION="DELETE_QUESTION";
export const DELETE_JOB_DATA="DELETE_JOB_DATA";
export const DELETE_MANAGER_DATA="DELETE_MANAGER_DATA";
