
export  const ADD_DEPARTMENT_QUESTIONS = "ADD_DEPARTMENT_QUESTIONS";
//  export  const ADD_MANAGER_QUESTIONS = ADD_MANAGER_QUESTIONS;
//  export const ADD_JOB_QUESTIONS = ADD_JOB_QUESTIONS; 
export const DELETE_DEPARTMENT_QUESTIONS = "DELETE_DEPARTMENT_QUESTIONS";
//  export  const DELETE_MANAGER_QUESTIONS = DELETE_MANAGER_QUESTIONS;
//  export const DELETE_JOB_QUESTIONS = DELETE_JOB_QUESTIONS;